Milestone 1: Set up GitHub and tools
Emmyn5600/NewYorkTime_Clone pull request #1
Opened 2021-02-17 20:13 UTC by Emmyn5600

This pull request contains the  following changes:

- Setting up Linters and tools
- Add a README file
- Add index.html file

2021-02-18 21:13 UTC, whiz25 requested changes
## Invalid PR 😞 
Hey @Emmyn5600 I appreciate the efforts you put into this project. Keep up!
However, I can not continue with the review because you have failing linter cases and therefore this is an invalid PR.
Please fix the failing linter cases and resubmit for another review.


### Martin Afani

2021-02-19 00:33 UTC, wathigo requested changes
## CHANGES REQUIRED :o: 
Great job on this project.
Let's address a few issues before we proceed. See the comments :point_down: 

**After making the necessary changes, submit another request for review.** 

**Happy Debugging :technologist: 
Simon Wathigo**

2021-02-19 00:33 UTC, wathigo commented on index.html
> +            <nav id="Head_logo" class="flex">
Let's improve styles on the nav section of the page:
* The icons have not been styled well. They should be centered inside a circular border.
* The search and hamburger icons are too small. 
* Space and Cosmos title should occupy one line.
* The text inside the login and subscribe buttons needs some margin on the left and right.

Clone Page | Original Page
|---------------:|:------------------|
![Screenshot from 2021-02-18 19-03-58](https://user-images.githubusercontent.com/44072711/108438197-c5e98b80-721c-11eb-8be6-e9974605ba0a.png) | ![original_nav](https://user-images.githubusercontent.com/44072711/108438227-d3067a80-721c-11eb-8009-24fe2062f322.png)

2021-02-19 00:33 UTC, wathigo commented on index.html
> +                <img src="./assets/cause1.png" alt=""></div>
The 'Theory of Inflation' section is quite different from the original page.
Have a look. Let's work on the styling.
Cloned Version | Original Version
|-------------------:|:----------------------|
![Screenshot from 2021-02-18 19-12-40](https://user-images.githubusercontent.com/44072711/108438851-1a413b00-721e-11eb-9183-59f28024d660.png) | ![original_inflation](https://user-images.githubusercontent.com/44072711/108438871-23320c80-721e-11eb-97f1-ee0f93b27a38.png)

2021-02-19 00:33 UTC, wathigo commented on index.html
> +                <section class="content_image_caption">NASA</section>
The bottom part is also completely different from what we have in the original version. Let's check out this :point_down: and make the necessary changes.
Cloned Version | Original Version
|--------------------:|:---------------------|
![Screenshot from 2021-02-18 19-22-07](https://user-images.githubusercontent.com/44072711/108439370-25489b00-721f-11eb-8b5d-538000d09b2a.png) | ![original_bottom](https://user-images.githubusercontent.com/44072711/108439400-31345d00-721f-11eb-9c21-b35e2bd97439.png)

2021-02-19 00:33 UTC, wathigo commented on index.html
> +<footer class="footer">
Lastly, we have a column missing from the footer.
Cloned Version | Original Version
---------------------:|:--------------------|
![Screenshot from 2021-02-18 19-27-18](https://user-images.githubusercontent.com/44072711/108439573-8c664f80-721f-11eb-8041-f4f4af7bec86.png) | ![original_footer](https://user-images.githubusercontent.com/44072711/108439593-95572100-721f-11eb-99d0-8ae11fcfe5f1.png)

2021-02-19 20:03 UTC, blackpintz requested changes
# Status: Changes Required 🛑

### Hello team 👋,

**Great job implementing the requested changes 👏.**

### Highlights

- **The page looks like the original.**
- **The code is clean.**

### Mandatory Requirements.

1). Improve the following sections so they look like the original page.

- **space & cosmos text on the navbar should appear on a single line.**
- **For the theory of inflation section, there should be some spacing on the left and right. Also, increase the size of the images.**
- **Fix the styling of the last column in the Footer section.**
- **Fix the alignment of the date captions in More in Space and Anatomy and Editor's pick sections.**
- 

2). **The new york times logo in the footer should be a link.**

### Happy coding 🥂.

**You can reach me on slack (Rose Wanjohi).**

2021-02-19 21:37 UTC, blackpintz approved these changes
# Status: Approved 🎉 

**Congratulations team 👏. Good luck with your next project 😃.**

2021-02-19 21:59 UTC, merged